### ISSUE TITLE
Provide example values

### ISSUE THREAD

**Issue by PanderMusubi** [grundid/relation-analyzer#26]
Please provide some examples at http://ra.osmsurround.org/ for:
- Relation ID
- Relation Name
- Relation Type
- Route
- Ref Tag
- Network
- Operator

That will each return a result that properly showcases this OSM Relation Analyzer

**Comment by grundid** [comment]
Hi. When you start typing into the fields you will see suggested values bases on the Tag Info Projekt.
https://taginfo.openstreetmap.org/

**Comment by PanderMusubi** [comment]
Thanks
