### ISSUE TITLE
The website seems to be down

### ISSUE THREAD

**Issue by rene78** [grundid/relation-analyzer#27]
Cannot access it for quite some time already.

**Comment by grundid** [comment]
Restarted the server. Should be working again.

**Comment by rene78** [comment]
Thanks! And thanks for developing this great tool by the way!

**Comment by hgcvm** [comment]
Website seems to be down again. Thanks for looking into it.

**Comment by grundid** [comment]
Restarted the server. Should be working again. Will add some checks to prevent this.
