### ISSUE TITLE
page seems down (http://ra.osmsurround.org)

### ISSUE THREAD

**Issue by sun-geo** [grundid/relation-analyzer#32]
http://ra.osmsurround.org

Same response by using different kind of browsers:

![image](https://user-images.githubusercontent.com/47290585/87795599-974fa080-c848-11ea-9797-028d3f1794f5.png)

**Comment by grundid** [comment]
Could you please verify again? The website is running.

**Comment by sun-geo** [comment]
Thanks for instant response & checking.
Used Firefox & Chrome for verification again. Same result. Maybe any other person could do the same check...

**Comment by sun-geo** [comment]
It's back on normal operation.
=> closed
Did you change anything?
