### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by kudlav** [grundid/relation-analyzer#35]
Unable to reach http://ra.osmsurround.org/

**Comment by SomeoneElseOSM** [comment]
http://ra.osmsurround.org/ seems to have returned just now?

**Comment by kudlav** [comment]
Hi, I don't understand to your comment. It's working now anyway, so it's time to close this issue.

**Comment by SomeoneElseOSM** [comment]
Sorry for using an English colloquialism - when a website is not working we might say it has "gone away" or "gone to sleep".
